config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'pages/terms'

  # Gets all events, and their associated nested resources
  resources :events do
    resources :jobs
    resources :event_days
    resources :applies
    resources :shifts
  end


  resources :event_days do
    resources :rotations
  end

  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  resources :users  do
    resources :events do
      resources :applies
    end
  end

  # Allows password to be updated
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :applies do
    get 'approve',            on: :member
    get 'accept_invitation',  on: :member
    get 'decline_invitation', on: :member
    get 'submitted'
    collection do
      post 'edit_multiple'
      put  'update_multiple'
    end
  end


  patch 'accept_multiple', to: 'applies#accept_multiple', as: :accept_multiple

  patch 'notify_multiple', to: 'event_days#notify_multiple', as: :notify_multiple

  patch 'notify_all', to: 'shifts#notify_all', as: :notify_all

  root to: "pages#home"
  # root to: "events#show", :id => Event.last.id
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  first_name             :string
#  last_name              :string
#  full_name              :string
#  birthday               :date
#  mobile_number          :string
#  slug                   :string
#  shifts_made            :integer          default(0)
#  shifts_missed          :integer          default(0)
#  apps_accepted          :integer          default(0)
#  hours_worked           :integer          default(0)
#  rating                 :float
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  medical_conditions     :text
#  provider               :string
#  uid                    :string
#  stripe_customer_id     :string
#  deleted_at             :datetime
#
# Indexes
#
#  index_users_on_deleted_at            (deleted_at)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_slug                  (slug) UNIQUE
#

class User < ApplicationRecord

  acts_as_paranoid

  # FIX_ME - this relationship is not setup properly at the minute
  # has_and_belongs_to_many :accepted_events, class_name: "Event"
  # has_and_belongs_to_many :applied_events, class_name: "Event"
  alias_attribute :applications, :apps

  has_many :apps, class_name: "Apply"

  has_one :emergency_contact
  accepts_nested_attributes_for :emergency_contact, :reject_if => :all_blank, :allow_destroy => true  

  # Enables roles for Users via the Rolify gem and CanCanCan gem
  rolify

  # Allows 'friendly' slugs
  extend FriendlyId
  friendly_id :full_name, use: :slugged

  # Allows a shift_manager role to be in charge of a specific rotation
  has_many :rotations, class_name: "Rotation", foreign_key: 'shift_manager_id'

  # Allows a shift to be assigned to a volunteer
  has_many :shifts, class_name: "Shift", foreign_key: 'volunteer_id'

  has_many :skills

  # Saves amounts charged to that person
  has_many :charges

  accepts_nested_attributes_for :skills, :reject_if => :all_blank, :allow_destroy => true  

  has_many    :volunteer_preferred_departments
  has_many    :preferred_departments, through: :volunteer_preferred_departments, source: :job_department

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  # Actions to take when saving User
  before_save :set_full_name
  after_create :assign_default_role
  after_create :add_emergency_contact

  # Model validations
  validates_presence_of :email

  # Sets the user's avatar from Paperclip gem
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
  # Validates that the avatar is a real image when uploaded
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  # Process the avatar as a background job, to not slow the user creation process.  delayed_paperclip gem
  process_in_background :avatar


  # send Devise emails through your existing queue by overriding the 
  # send_devise_notification method in your model
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def age
    if self.birthday?
      dob = self.birthday
      now = Time.now.utc.to_date
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    else
      "-"
    end

  end

  def select_label
    return "#{self.full_name} (#{self.email})"
  end

  # defines information received when user signs in with Facebook link
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # Extracts the first and last name from omniauth's name
      full = auth.info.name.split
      user.first_name = full[0]
      full.delete_at(0)
      user.last_name = full * ' '

      # Sets the email, password, and avatar for the user
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.avatar = auth.info.image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end

  protected

    # Sets the user's full name on save
    def set_full_name
      unless self.first_name.nil? or self.last_name.nil?
        self.full_name = "#{self.first_name.capitalize} #{self.last_name.capitalize}"
      else
        self.full_name = "#{self.first_name} #{self.last_name}"
      end
    end

    # Assigns default role of :volunteer when user is created (Rollify gem + CanCanCan)
    def assign_default_role
      self.add_role(:volunteer) if self.roles.blank?
    end  

    # Creates an empty emergency contact for the new user
    def add_emergency_contact
      contact = EmergencyContact.create(user_id: self.id, name: "", phone_number: "", )
    end      
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  #Sets a layout for account pages
  layout "login"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    if params[:ref] == "apply"
      new_event_apply_path(@current_event.id)
    else
      super(resource)
    end
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end  
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  #Sets a layout for account pages
  layout "login"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # Only allows access if use has correct role
  before_action :client_and_up, only: [:index, :show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :stripe_customer, only: [:show, :edit]
  before_action :get_apps, only: [:show, :edit]
  before_action :get_shifts, only: [:show, :edit]
  layout "account", only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    # @users = User.all
    @managers = User.with_role(:shift_manager)
    @volunteers = User.with_role(:volunteer)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @recently_accepted = @apps.accepted.where('updated_at >= ?', 2.months.ago).count
    if @recently_accepted > 0 && flash.empty?
      flash[:notice] = "You have an accepted application pending your confirmation! Your spot is not secure until you confirm your intent to attend your shifts."
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to edit_user_path(@user), notice: 'Your profile was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    if params[:stripeToken]
    # User is updating their card details
      if @user.stripe_customer_id
        #User is in Stripe, retrieve them
        customer = StripeTool.find_customer(@user.stripe_customer_id)
        # Adds The New Card
        card = StripeTool.add_card(customer, params[:stripeToken])

        error = card[:error] ? card[:error][:message] : nil

        # Don't proceed without a valid card
        if error
          redirect_to edit_user_path(@user), flash: { "alert-warning": "Oops, something went wrong; please check the details and try again#{error ? '. (Card error: ' + error + ')' : ''}" }
          return
        else
          # Continue
        end
      else
        # Creates the customer via Stripe API
        customer = StripeTool.create_customer(@user.email, params[:stripeToken])
        # Sets the user's Stripe Account ID
        @user.update_attributes(stripe_customer_id: customer.id)
      end
    end
      
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_user_path(@user), notice: 'Your profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Your profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    def stripe_customer
      @customer = @user.stripe_customer_id ? StripeTool.find_customer(@user.stripe_customer_id) : nil
    end

    def get_apps
      @apps = @user.applications.includes(:event)
    end

    def get_shifts
      @shifts = @user.shifts.includes(:event_day, :job)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name,
                                   :avatar,
                                   :last_name,
                                   :email,
                                   :birthday,
                                   :mobile_number,
                                   :password,
                                   :password_confirmation,
                                   :current_password,
                                   skills_attributes: [:id, :name, :proof_document, :_destroy])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_applications.haml
- if @apps.empty?
  .user-details.panel.default
    .row
      .col-md-12
        %small.form-text.text-muted You don't have any current applications. Check back soon for new events to apply for.
- @apps.each do |app|
  .user-details.panel.default
    .row
      .col-md-4
        %h6= app.event.name
      .col-md-5.pad-me
        Your Application Status:
        %span.label{ class: "label-#{app.status_label}" }
          = app.state.titleize
      .col-md-3.pad-me
        / # = link_to 'Edit my application', edit_apply_path(app)
        %i Applications are closed
      %br
      %hr

      / 
        Cover the different states the app could be in

      - if app.submitted?
        /
          This app is in the basic 'submitted state'
        .col-xs-12
          We have successfully received your application - thank you for applying!
        %br
        %hr
        .col-xs-2
          = "Actions:"
        .col-xs-10
          %div
            %span.small.form-text.text-muted
              Please hang tight while we review the applications - you'll receive emails with further instructions.
            = link_to "Delete application", decline_invitation_apply_path(app), class: "small form-text", data: { confirm: "Are you sure? You won't be able to recover this application" }

      - elsif app.accepted?
        /
          This app has been accepted but not yet confirmed
        .col-xs-12
          Congrats, your application has been accepted by our team!  You still need to confirm your intent to volunteer below.
        %br
        %hr
        .col-xs-2
          = "Actions:"
        .col-xs-10
          - unless @customer && @customer.sources.total_count > 0
            %div
              %span{ title: "You need to add a payment method to confirm your spot", style: "display: inline-block", data: { toggle: "tooltip" } }
                = link_to "Confirm my spot", accept_invitation_apply_path(app), class: "btn btn-lg btn-success disabled", disabled: true, data: { confirm: "Securing your spot requires a $15 volunteer t-shirt purchase; this will be charged to your card." }
              = link_to "Decline", decline_invitation_apply_path(app), class: "btn btn-lg btn-default", data: { confirm: "Are you sure? You won't be able to recover this application" }
            %div.pad-top
              %span.small.form-text.text-muted
                %i
                  It appears we don't have a saved credit card for your account. You need to add a payment method below to secure your spot.
          - else
            = link_to "Confirm my spot", accept_invitation_apply_path(app, key: SecureRandom.uuid), class: "btn btn-success", data: { confirm: "Securing your spot requires a $15 volunteer t-shirt purchase; this will be charged to your card." }
            = link_to "Decline", decline_invitation_apply_path(app), class: "btn btn-default", data: { confirm: "Are you sure? You won't be able to recover this application" }

      - elsif app.confirmed?
        /
          This app has been confirmed and paid by the user
        .col-xs-12
          Awesome! You have confirmed your intention to volunteer and your spot is secure.
        %br
        %hr
        .col-xs-2
          = "Actions:"
        .col-xs-10
          %div
            %span.small.form-text.text-muted
              Welcome to the team.  Watch your email for important announcements about your shift schedule or upcoming meetings.
            %br
            %a.small.form-text{ data: { target: '#myModal', toggle: 'modal'} }
              Want to cancel your shift?
            - deadline = app.event.deadline_to_decline
            #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog.modal-lg{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#exampleModalLabel.modal-title I'm unable to make my shift, what are my options?
                    %hr
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    - if app.before_deadline?
                      %h5
                        = " The deadline to decline your spot is: #{deadline.strftime("%A")}, #{deadline.strftime("%d/%m/%Y")}"
                      %br
                      %h6
                        You are still able to decline your volunteer position below; after the cutoff cancellations are subject to the fee stated in your application terms.
                      %i.small
                        Unfortunately we are unable to refund application fees.
                      %br
                      %br
                      = link_to "Confirm Cancellation", decline_invitation_apply_path(app), class: "btn btn-info", data: { confirm: "Are you sure? Your event ticket will no longer be valid and your application will be deleted" }
                    - else
                      %h5
                        = " The deadline to decline your spot was: #{deadline.strftime("%A")}, #{deadline.strftime("%d/%m/%Y")}"
                      %br
                      %h6
                        You are now unable to decline your volunteer position.  Please contact our team at #{app.event.primary_contact_email} to discuss your options.

                  .modal-footer
                    %button.btn.btn-info{"data-dismiss" => "modal", :type => "button"} Keep my spot

      - elsif app.waitlisted?
        /
          This app is 'waitlisted'
        .col-xs-12
          We've had a ton of great applications and we've placed yours on the waitlist for the minute.  We'll be releasing a second round of offers soon.
        %br
        %hr
        .col-xs-2
          = "Actions:"
        .col-xs-10
          %div
            %span.small.form-text.text-muted
              Please watch your email for second round offers.
            = link_to "Delete application", decline_invitation_apply_path(app), class: "small form-text", data: { confirm: "Are you sure? You won't be able to recover this application" }

      - elsif app.denied?
        /
          This app is 'waitlisted'
        .col-xs-12
          We've had a massive amount of applications and unfortunately were not able to accept yours at this time.  Thank you for making the effort and we encourage you to come back and apply for future events.
        %br
        %hr
        .col-xs-2
          = "Actions:"
        .col-xs-10
          %div
            %span.small.form-text.text-muted
              Please watch your email to hear about upcoming festivals with volunteer opportunities.
            = link_to "Delete application", decline_invitation_apply_path(app), class: "small form-text", data: { confirm: "Are you sure? You won't be able to recover this application" }

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  %h5
    Contact Details
  .user-details.panel.default
    .row
      .col-md-6
        = f.input :first_name
      .col-md-6
        = f.input :last_name
      .col-md-6
        = f.input :email
      .col-md-6
        = f.input :mobile_number
      .col-md-6
        = f.input :birthday, start_year: 60.years.ago.year, end_year: 18.years.ago.year, required: true, order: [:day, :month, :year]
      .col-md-12.text-right
        = f.button :submit, "Update Details"

app/views/users/_onboard_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .inputs
    / = f.input :first_name
    / = f.input :last_name
    / = f.input :full_name
    = f.input :email
    = f.input :birthday
    = f.input :mobile_number
    = f.input :slug
    = f.input :shifts_made
    = f.input :shifts_missed
    = f.input :apps_accepted
    = f.input :hours_worked
    = f.input :rating

  .actions.text-right
    = f.button :submit

app/views/users/_payment_methods.haml
.row
  .col-md-12
    %h5
      Payment Methods
.user-details.panel.default
  .row
    .col-md-12
      %small.form-text.text-muted All volunteer applications require a payment method to secure your spot. You'll need a valid card to accept apply for positions or accept offered positions.
  - if @customer && @customer.sources.total_count > 0
    .row
      .col-md-12
        %table.table.table-hover
          %thead
            %tr
              %td
                Card
              %td
                Last 4
              %td
                Expiry
          %tbody
            - @customer.sources.each do |card|
              %tr
                %td
                  %i
                    = card.brand
                %td
                  %i
                    = card.last4
                %td
                  %i
                    = "#{card.exp_month}/#{card.exp_year}"
        
  .row.pad-top
    .col-xs-4
      %a{class: "btn btn-default js-add-card"}
        = @customer && @customer.sources.total_count > 0 ? "+ Update card" : "+ Add Card"
    .col-xs-8.align-right
      =image_tag("powered_by_stripe.png")
  = simple_form_for @user, :html=> { class: "js-payment-form hidden" } do |f|
    = f.hidden_field :stripe_customer_id
    .inputs.row
      .col-md-12
        :javascript
          Stripe.setPublishableKey('#{ENV['STRIPE_PUBLISHABLE_KEY']}');
          console.log(Stripe);

        %span.payment-errors

    .inputs.row
      .col-xs-12.col-sm-6
        .form-group  
          %label
            %span Name
          %input{"data-stripe" => "name", :type => "text", class: "form-control", required: true, value: @user.full_name }
      .col-xs-12.col-sm-6
        .form-group  
          %label
            %span Card Number
          %input{"data-stripe" => "number", :type => "text", class: "form-control", required: true}   
      .col-xs-12.col-sm-4
        .form-group  
          %label
            %span CVC
          %input{"data-stripe" => "cvc", :size => "4", :type => "text", class: "form-control", required: true }
      .col-xs-12.col-sm-3
        .form-group  
          %label
            %span Expiration (MM/YY)
          .form-inline
            %input{"data-stripe" => "exp-month", :size => "2", :type => "text", class: "form-control", required: true}
            %span /
            %input{"data-stripe" => "exp-year", :size => "2", :type => "text", class: "form-control", required: true}
      .col-xs-12.col-sm-4
        .form-group  
          %label
            %span Postcode
          %input{"data-stripe" => "address_zip", :size => "5", :type => "text", class: "form-control", required: true}

    .actions
      %div
        %button{type: "submit", class: "btn btn-default js-submit"}
          Submit
        / # = f.button :submit, "Submit"
  .row
    .col-md-12
      %hr
      %span.small
        This site is developed by web agency 'Built in Code'. Charges will show up in your bank from Built in Code LLC.

app/views/users/_shifts.haml
- if @shifts.empty?
  .user-details.panel.default
    .row
      .col-md-12
        %small.form-text.text-muted You don't have any current shifts. You'll be notified by email when you are assigned a shift.

- @shifts.each do |shift|
  - event = shift.event_day.event

  .user-details.panel.default
    .row
      .col-md-3
        %h6
          = "#{shift.job.title} @ #{event.name}"
      .col-md-6.pad-me
        = shift.start_time.strftime("%l:%M %p %A %Y-%m-%d")
      .col-md-3.pad-me
        = "#{shift.length}hrs"
      %br
      %hr

      .col-xs-12
        %div
          Your shift has been assigned.

      %br
      %hr

      .col-xs-2
        %div
          = "#{shift.job.title}"
      .col-xs-10
        %div
          = "#{shift.job.description}"

      %br
      %hr
      .col-xs-2
        = "Actions:"
      .col-xs-10
        %div
          %span.small.form-text.text-muted
            = "- If you have questions about your shift, please contact #{event.primary_contact_email}."
        %div
          %span.small.form-text.text-muted
            = "- You must report to your shift by #{shift.start_time.strftime("%l:%M %p")} at #{shift.job.meeting_place} and work the entire #{shift.length} hours in order to qualify for your festival ticket."

app/views/users/_skill_fields.haml
.nested-fields
  = f.input :name
  = f.input :proof_document
  = link_to_remove_association "- remove skill", f

app/views/users/_user_table.haml
%table.table
  %thead
    %tr
      %th Full name
      %th Email
      %th Age
      %th Mobile number
      %th Hours worked
      %th Rating
      %th
      %th

  %tbody
    - users.each do |user|
      %tr
        %td= user.full_name
        %td= user.email
        %td= user.age
        %td= user.mobile_number
        %td= user.hours_worked
        %td= user.rating
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)

app/views/users/edit.html.haml
/ Renders the header section content
- content_for :page_title do
  %h1 Manage Your Account
- content_for :page_sub_title do
  %p It's easy to manage your account.  Quickly access or update your information.

/ Renders the user's details
- content_for :profile do
  = render "user_details"

%h5
  My Applications
= render 'applications'

%h5
  Shifts
= render 'shifts'

= render 'payment_methods'

= render 'form'


= render 'users/registrations/cancel_account'

/ %hr

/ = link_to 'Show', @user
/ \|
/ = link_to 'Back', users_path

app/views/users/index.html.haml
- content_for :hero_title do
  = "Volunteers & Managers"
  %br
  %h3= "for: #{@current_event.name}"

.col-md-12.event_header
  .panel.default
    .top-key-factor
      .event_day__inner
        / Nav tabs
        %ul.nav.nav-tabs{:role => "tablist"}
          %li.nav-item.active
            %a.nav-link.active{"data-toggle" => "tab", :href => "#volunteers", :role => "tab"}
              Volunteers
          %li.nav-item
            %a.nav-link{"data-toggle" => "tab", :href => "#managers", :role => "tab"}
              Managers
        / Tab panes
        .tab-content
          #volunteers.tab-pane.active{:role => "tabpanel"}
            = render 'user_table', users: @volunteers

          #managers.tab-pane{:role => "tabpanel"}
            = render 'user_table', users: @managers     


%br

/ = link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path