config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'pages/terms'

  # Gets all events, and their associated nested resources
  resources :events do
    resources :jobs
    resources :event_days
    resources :applies
    resources :shifts
  end


  resources :event_days do
    resources :rotations
  end

  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  resources :users  do
    resources :events do
      resources :applies
    end
  end

  # Allows password to be updated
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :applies do
    get 'approve',            on: :member
    get 'accept_invitation',  on: :member
    get 'decline_invitation', on: :member
    get 'submitted'
    collection do
      post 'edit_multiple'
      put  'update_multiple'
    end
  end


  patch 'accept_multiple', to: 'applies#accept_multiple', as: :accept_multiple

  patch 'notify_multiple', to: 'event_days#notify_multiple', as: :notify_multiple

  patch 'notify_all', to: 'shifts#notify_all', as: :notify_all

  root to: "pages#home"
  # root to: "events#show", :id => Event.last.id
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                         :uuid             not null, primary key
#  start_time                 :datetime
#  end_time                   :datetime
#  event_length               :float
#  ticket_price_cents         :integer
#  client_owner_id            :uuid
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  name                       :string
#  slug                       :string
#  application_closing_date   :datetime
#  initial_charge_description :string
#  initial_charge_cents       :integer
#  deleted_at                 :datetime
#  deadline_to_decline        :datetime
#  primary_contact_email      :string
#
# Indexes
#
#  index_events_on_client_owner_id  (client_owner_id)
#  index_events_on_deleted_at       (deleted_at)
#  index_events_on_slug             (slug)
#

class Event < ApplicationRecord

  acts_as_paranoid

  belongs_to              :client_owner, class_name: "User"
  has_many                :event_days

  # FIX_ME - this relationship is not setup properly at the minute
  # has_many                :accepted_volunteers, class_name: "User"
  # has_many                :applied_volunteers, class_name: "User"

  has_many                :applications, class_name: "Apply"

  # Allows 'friendly' slugs
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Allows nested forms to add jobs for an event
  has_many                :jobs

  # Saves amounts charged to that event
  has_many :charges

  accepts_nested_attributes_for :jobs, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of   :name, :start_time, :end_time, :ticket_price_cents
  before_create             :set_event_length
  before_create             :set_deadline_to_decline
  after_save                :create_event_days


  private

  # Sets a default deadline to decline applications, after which
  # the user is charged for not showing up
  def set_deadline_to_decline
    self.deadline_to_decline = ( Time.now + 6.months ) unless self.deadline_to_decline.present?
  end

  # Sets the length of the event based on the start and end times
  def set_event_length
    # Get event length in seconds, convert to hours
    self.event_length = (self.end_time - self.start_time)/(60*60)
  end

  # Creates days for each event, that can be used for scheduling
  def create_event_days
    unless self.start_time.nil? && self.end_time.nil?
      @days = []
      first = self.start_time.to_date
      last = self.end_time.to_date
      duration = (last-first).to_i

      i = 0

      # Adds each day of event into the days array
      until i > duration do
        @days << (first + i.days)
        i += 1
      end

      @days.each do |day|
        props = {
          event_id: self.id,
          date: day
        }
        EventDay.where(props).first_or_create
      end
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # load_and_authorize_resource
  # Basic Devise authentication
  before_action :authenticate_user!
  # Only allows access if use has correct role
  before_action :client_and_up
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event_days = @event.event_days
    @days_by_date = @event_days.group_by(&:date)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    # Get all the event_days as well for each request
    def set_event
      @event = Event.includes(:event_days).friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_time, :end_time, :event_length, :ticket_price_cents, :client_owner_id,
                                    jobs_attributes: [:id, :title, :description, :rotations_required_per_day, :workers_per_rotation, :hours_per_rotation, :_destroy,
                                    skill_requirements_attributes: [:id, :title, :description, :_destroy]
                                    ])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.haml
.col-md-4.col-sm-6.col-xs-12.event_day
  .panel.default
    .top-key-factor
      .badge-container
        %span.badge.excellent EXCELLENT
      .centerify-icon
        %span.icon
          / %img{:alt => "icon", "ng-src" => "images/icons/payment-history.svg", :src => "images/icons/payment-history.svg"}/
      .event_day__title
        = link_to(event.name, event_path(event))
        %hr
      .event_day__inner        
        - if user_signed_in?
          / =  current_user.applications
          = link_to "Apply to volunteer", new_user_event_apply_path(current_user.id, event.id), class: "btn btn-info"
      .event_day__inner
        = "Start date: "
        = event.start_time        
      .event_day__inner
        = "Owner: "
        = link_to(event.client_owner.full_name, user_path(event.client_owner))
      .event_day__inner
        = "Schedule Shifts: "
        - event.event_days.each do |day|  
          = link_to(day.date.strftime("%A"), event_event_day_path(event,day.id))
      .event_day__inner
        = link_to("Jobs: #{event.jobs.count}", event_jobs_path(event))
      .event_day__inner
        = link_to("Applications Received: #{event.applications.count}", event_applies_path(event))      
      .event_day__inner
        = "Shifts Filled: #{}  "    

/     %button.btn.btn-info{"data-target" => "##{event.name.downcase.delete(' ')}", "data-toggle" => "modal", :type => "button"}
/       Apply to event
/ .modal.fade{:id => event.name.downcase.delete(' ') }
/   .modal-dialog{:role => "document"}
/     .modal-content
/       .modal-header
/         %h5.modal-title Apply to volunteer at #{event.name}
/         %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
/           %span{"aria-hidden" => "true"} ×
/       / = simple_form_for day, url: event_event_day_path(@event, day) do |f|
/       /   .modal-body

/       /     = f.association :jobs


/       .modal-footer
/         / = f.button :submit
/         %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close          

app/views/events/_event_header.haml
.col-md-12.event_header
  .panel.default
    .top-key-factor
      .event_day__inner
        %table.table
          %thead
            %tr
              %td
                Start date
              %td
                Owner
              %td
                Jobs (#{event.jobs.count})
              %td
                Applicants (#{event.applications.count})
              %td 
                Shifts
          %tbody 
            %tr
              %td
                = "#{event.start_time.strftime("%A, %d/%m/%Y")}"
              %td
                = link_to(event.client_owner.full_name, user_path(event.client_owner))
              %td   
                = link_to("View / Add", event_jobs_path(event), class: "btn btn-sm btn-default")  
              %td
                = link_to("Review / Aprove", event_applies_path(event), class: "btn btn-sm btn-default") 
              %td   
                TODO

/     %button.btn.btn-info{"data-target" => "##{event.name.downcase.delete(' ')}", "data-toggle" => "modal", :type => "button"}
/       Apply to event
/ .modal.fade{:id => event.name.downcase.delete(' ') }
/   .modal-dialog{:role => "document"}
/     .modal-content
/       .modal-header
/         %h5.modal-title Apply to volunteer at #{event.name}
/         %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
/           %span{"aria-hidden" => "true"} ×
/       / = simple_form_for day, url: event_event_day_path(@event, day) do |f|
/       /   .modal-body

/       /     = f.association :jobs


/       .modal-footer
/         / = f.button :submit
/         %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close          

app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :start_time
    = f.input :end_time
    / = f.input :event_length
    = f.input :ticket_price_cents
    = f.association :client_owner

  .actions.text-right
    = f.button :submit

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %thead
    %tr
      %th Start time
      %th End time
      %th Event length
      %th Ticket price cents
      %th User
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.start_time.strftime("%A %l:%M%p")
        %td= event.end_time.strftime("%A %l:%M%p")
        %td= event.event_length
        %td= event.ticket_price_cents
        %td= event.client_owner
        %td= link_to 'Show', event
        %td= link_to 'Edit', edit_event_path(event)
        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
- content_for :hero_title do
  = @event.name
- content_for :cta do
  = link_to('Create jobs for this event', event_jobs_path(@event), class: 'btn btn-lg btn-success')
  = link_to("Manage applications", event_applies_path(@event), class: 'btn btn-lg btn-success')
  = link_to('Edit Event', edit_event_path(@event), class: 'btn btn-lg btn-success')
  = link_to "Apply to volunteer", new_event_apply_path(@event), class: "btn btn-info btn-lg" 
.row
  = render partial: "events/event_header", locals: {event: @event}

.row#event
  .col-md-12.event_body
    - unless @days_by_date.empty?
      %h4
        = @days_by_date.values.first[0][:date].strftime("%B, %Y")
      = calendar(@days_by_date.keys.first, @days_by_date.keys.last) do |date|
        = date.day
        - if @days_by_date[date]
          = render partial: "event_days/day", collection: @days_by_date[date]