config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'pages/terms'

  # Gets all events, and their associated nested resources
  resources :events do
    resources :jobs
    resources :event_days
    resources :applies
    resources :shifts
  end


  resources :event_days do
    resources :rotations
  end

  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  resources :users  do
    resources :events do
      resources :applies
    end
  end

  # Allows password to be updated
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :applies do
    get 'approve',            on: :member
    get 'accept_invitation',  on: :member
    get 'decline_invitation', on: :member
    get 'submitted'
    collection do
      post 'edit_multiple'
      put  'update_multiple'
    end
  end


  patch 'accept_multiple', to: 'applies#accept_multiple', as: :accept_multiple

  patch 'notify_multiple', to: 'event_days#notify_multiple', as: :notify_multiple

  patch 'notify_all', to: 'shifts#notify_all', as: :notify_all

  root to: "pages#home"
  # root to: "events#show", :id => Event.last.id
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/shift.rb
# == Schema Information
#
# Table name: shifts
#
#  id           :uuid             not null, primary key
#  rotation_id  :uuid
#  volunteer_id :uuid
#  length       :integer          default(1)
#  count        :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  event_day_id :uuid
#  job_id       :uuid
#  start_time   :datetime
#  state        :string
#
# Indexes
#
#  index_shifts_on_event_day_id  (event_day_id)
#  index_shifts_on_job_id        (job_id)
#  index_shifts_on_rotation_id   (rotation_id)
#  index_shifts_on_volunteer_id  (volunteer_id)
#

class Shift < ApplicationRecord

  # Includes State Machine Concern
  include ShiftStateMachine
  belongs_to :rotation
  belongs_to :event_day
  belongs_to :job

  # Allows optional volunteer owner, as this will not not set when created
  belongs_to :volunteer, class_name: 'User', foreign_key: 'volunteer_id', optional: true
  # has_one    :shift_rating  
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    @shifts = Shift
      .includes(:volunteer, :rotation, :job)
      .paginate(page: params[:page], per_page: 50)
    @event = @current_event
  end

  def notify_all
    @shifts = Shift.joins(:volunteer).where(state: 'created')
    respond_to do |format|
      if @shifts.each { |a| a.assign_vol! }
        format.html { redirect_to request.referrer, notice: 'The volunteers have been notified!' }
      else
        format.html { redirect_to request.referrer, flash: { "alert-warning": "Oops, something went wrong; please try again." } }
      end
    end
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_shift.haml
%tr
  %td
    - if shift.volunteer
      = link_to shift.volunteer.full_name, shift.volunteer
    - else
      None Assigned
  %td
    - if shift.job
      = shift.job.title
    - else
      No Job Title
  %td
    - if shift.start_time
      = shift.start_time.strftime("%A %l:%M%p")
    - else
      No Start Time Set
  %td
    - if shift.length
      = "#{shift.length} hrs"
    - else
      No length set

app/views/shifts/index.haml
- content_for :hero_title do
  = "Volunteer Shifts (Paged)"
  %br
  %h3= "for: #{@event.name}"

.col-md-12.upper_header
  .panel.default
    .top-key-factor
      .event_day__inner.row.filters
        .col-md-4.text-left
          / = form_tag applies_path(@event), method: 'get' do
          /   .input-group
          /     = text_field_tag "q", params[:q] ? params[:q] : nil, class: "form-control", placeholder: "Name or Email"
          /     %span.input-group-btn
          /       = submit_tag("Search", class: "btn btn-default")
        .col-md-2.text-right
          / %label{for: "job[:slug]"}
          /   Job Preference
          / = form_tag applies_path(@event), method: 'get' do
          /   = hidden_field_tag "view", @view_type == "paged" ? "" : "all"
          /   = hidden_field_tag "status", params[:status] ? params[:status] : nil
          /   = hidden_field_tag "q", params[:q] ? params[:q] : nil
          /   = hidden_field_tag "assign[slug]", params[:assign] ? params[:assign][:slug] : nil
          /   = collection_select(:job, :slug, @event.jobs, :slug, :title, {selected: params[:job] ? params[:job][:slug] : nil, include_blank: "All roles"}, class: "form-control")
        .col-md-2.text-right
          / %label{for: "job[:slug]"}
          /   Job Assignment
          / = form_tag applies_path(@event), method: 'get' do
          /   = hidden_field_tag "view", @view_type == "paged" ? "" : "all"
          /   = hidden_field_tag "status", params[:status] ? params[:status] : nil
          /   = hidden_field_tag "job[slug]", params[:job] ? params[:job][:slug] : nil
          /   = hidden_field_tag "q", params[:q] ? params[:q] : nil
          /   = collection_select(:assign, :slug, @event.jobs, :slug, :title, {selected: params[:assign] ? params[:assign][:slug] : nil, include_blank: "All roles"}, class: "form-control")
        .col-md-2.text-right
          / %label{for: "job[:slug]"}
          /   Application Status
          / = form_tag applies_path(@event), method: 'get' do
          /   = hidden_field_tag "view", @view_type == "paged" ? "" : "all"
          /   = hidden_field_tag "job[slug]", params[:job] ? params[:job][:slug] : nil
          /   = hidden_field_tag "assign[slug]", params[:assign] ? params[:assign][:slug] : nil
          /   = hidden_field_tag "q", params[:q] ? params[:q] : nil
          /   %select{name: 'status', class: 'form-control', id: 'status_selector'}
          /     %option{value: 'all_states'}
          /       = "All States"
          /     - @statuses.each do |status|
          /       %option{ value: status, selected: params[:status] && params[:status] == status ? 'selecte' : nil }
          /         = status.titleize
          /       }
        .col-md-2.text-right
          / - if @view_type == "paged"
          /   = link_to "View all ->", event_applies_path(@event, view: "all")
          / - else
          /   = link_to "View paged ->", event_applies_path(@event)
  .panel.default
    .top-key-factor
      .event_day__inner.row.filters
        .col-md-3.text-left
          = "Total shifts: #{@count}"
        .col-md-3.text-left
          = "Assigned shifts: #{@assigned}"
        .col-md-3.text-right
          = "Completed Shifts: #{@completed}"
        .col-md-3.text-right
          = "Missed shifts: #{@missed}"
.col-md-12.event_header
  .panel.default
    .top-key-factor
      .event_day__inner
        / = form_tag(assign_multiple_path, method: :patch) do
        %table.table.table-hover
          %thead
            %tr.sortable
              %td
                Volunteer
              %td
                Job Title
              %td
                Start Time
              %td
                Duration
          %tbody
            = render partial: "shift", collection: @shifts

.col-md-12.lower_footer
  / -if @view_type == "paged"
  .panel.default.with-pagination
    .top-key-factor
      .event_day__inner
        = will_paginate @shifts
  .panel.default
    .top-key-factor
      .event_day__inner
        / = link_to "Download All", applies_path(@event, format: :csv), class: "btn btn-default"
        = link_to("Notify Vols", notify_all_path, method: :patch, data: { confirm: "Are you sure? This will notify volunteers via email of their shift assignments" }, class: "btn btn-sm btn-primary")