config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'pages/terms'

  # Gets all events, and their associated nested resources
  resources :events do
    resources :jobs
    resources :event_days
    resources :applies
    resources :shifts
  end


  resources :event_days do
    resources :rotations
  end

  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  resources :users  do
    resources :events do
      resources :applies
    end
  end

  # Allows password to be updated
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :applies do
    get 'approve',            on: :member
    get 'accept_invitation',  on: :member
    get 'decline_invitation', on: :member
    get 'submitted'
    collection do
      post 'edit_multiple'
      put  'update_multiple'
    end
  end


  patch 'accept_multiple', to: 'applies#accept_multiple', as: :accept_multiple

  patch 'notify_multiple', to: 'event_days#notify_multiple', as: :notify_multiple

  patch 'notify_all', to: 'shifts#notify_all', as: :notify_all

  root to: "pages#home"
  # root to: "events#show", :id => Event.last.id
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.haml
%footer.footer
  .container-fluid
    %p 
      = "© Volunteer Management Platform #{Time.now.year}"

app/views/layouts/_header.haml
.header.clearfix
  .container-fluid
    %nav.header-inner
      %ul.nav.nav-pills.float-right
        - if current_user && current_user.has_role?(:admin || :event_client || :shift_manager)
          %li.nav-item
            = link_to(@current_event.name, @current_event, class: "nav-link #{active_class(@current_event)} #{active_class(root_path)}")
        - if current_user && current_user.has_role?(:admin || :event_client)
          %li.nav-item
            = link_to("Applications", event_applies_path(@current_event), class: "nav-link #{active_class(event_applies_path(@current_event))}")
          / %li.nav-item
          /   = link_to("Volunteers", users_path, class: "nav-link #{active_class(users_path)}")
          %li.nav-item
            = link_to("Shifts", event_shifts_path(@current_event), class: "nav-link #{event_event_days_path(@current_event)}")
        %li.nav-item
          = link_to("Terms", pages_terms_path, class: "nav-link #{active_class(pages_terms_path)}")
        = render 'users/menu/registration_items'
        = render 'users/menu/login_items'
      %ul.nav.nav-pills
        = link_to @current_event, class: "nav-link #{active_class(root_path)}" do
          = image_tag("logos/strawberry-fields-white.png", class: "header-logo")

app/views/layouts/account.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Volunteer Management Platform
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://js.stripe.com/v2/', 'data-turbolinks-track': 'reload'
  %body{ class: "#{controller.action_name} " "#{controller.controller_path}" }
    / Renders the global header
    = render "layouts/header"
    / Mastead - Title & subtitle
    %main
      .jumbotron
        / .full-overlay
        .container-fluid
          = flash_messages
          %h1.display-3
            = yield :page_title
          %p.lead
            = yield :page_sub_title
          = yield :cta
      .container-fluid
        .row.marketing
          .col-lg-4
            = yield :profile
          .col-lg-8
            = yield
    / Renders the global footer
    = render "layouts/footer"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Volunteer Management Platform
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://js.stripe.com/v2/', 'data-turbolinks-track': 'reload'
    / = javascript_pack_tag 'application'
  %body{ class: "#{controller.action_name} " "#{controller.controller_path}" }
    / Renders the global header
    = render "layouts/header"
    %main
      .jumbotron
        / .full-overlay
        .container-fluid
          = flash_messages 
          %h1.display-3
            = yield :hero_title
          %p.lead Strawberry Fields volunteer management application.  Please direct any questions to volunteers@strawberry-fields.com.au
          = yield :cta
          / %p
          /   - if user_signed_in?
          /     = link_to('Edit your account', edit_user_registration_path, class: 'btn btn-lg btn-success')
          /   - else
          /     = link_to('Become a volunteer', new_user_registration_path, class: 'btn btn-lg btn-success')
          .row
            = yield :hero_content
      .container-fluid
        .row.marketing
          .col-lg-12
            = yield
    / Renders the global footer
    = render "layouts/footer"

app/views/layouts/landing.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Volunteer Management Platform
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / # = javascript_pack_tag 'application'
  %body
    / Renders the global header
    / = render "layouts/header"
    %main
      .jumbotron.full-page
        .full-overlay
        .container-fluid.top-fixed
          .row
            .col-lg-12
              = flash_messages
        .container-fluid 
          %h1.display-3
            = yield :hero_title
        .container-fluid.bottom-fixed
          = yield

app/views/layouts/login.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Volunteer Management Platform
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    / Renders the global header
    = render "layouts/header"
    %main
      .container-fluid.login
        .row
          .col-lg-12
            = flash_messages
          .col-md-8.col-md-offset-2
            .title-wrap
              = yield :login_title
          .col-lg-12
            = yield
    / Renders the global footer
    = render "layouts/footer"